@startuml
[*] --> Login : Not Logged In
Login --> LandingPage : Login
LandingPage --> AllEventsPage : View Your Events
LandingPage --> CreateEventPage : Create an Event
AllEventsPage --> PastEventsPage : View Past Events
AllEventsPage --> DetailedEventPage : Click on Event
CreateEventPage --> AllEventsPage : After Creation of Event
DetailedEventPage --> ManageEventPage : Edit Event
PastEventsPage --> PastDetailedEventPage : Click on Event
PastDetailedEventPage --> AddHighlightsPage : Add Highlights
@enduml